name: ReportPlayer
main: nurazliyt\reportplayer\Main
version: 1.0.0
api: 5.0.0
author: NurAzliYT
commands:
  report:
    description: Report a player
    usage: /report <player>
  reportlist:
    description: List all pending reports
    usage: /reportlist
permissions:
  reportplayer.viewlist:
    description: "Allows viewing the report list"
    default: op
