name: ReportPlayer
main: nurazliyt\reportplayer\Main
version: 1.0.0
api: 5.0.0
author: NurAzliYT
commands:
  report:
    description: Report a player
    permission: reportplayer.commands
  reportlist:
    description: List all pending reports
    permission: reportplayer.viewlist
permissions:
  reportplayer.commands:
    description: "Allows player to report player"
    default: true
  reportplayer.viewlist:
    description: "Allows operator viewing the report list"
    default: op
